name: Docker Image CI

on:
  workflow_dispatch:
  
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Set Image tag
      run: |
        echo "IMAGE_TAG=$(date +%s)" >> $GITHUB_ENV        
        
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --tag ghcr.io/bognarpal/webtest4azure:$IMAGE_TAG --tag ghcr.io/bognarpal/webtest4azure:latest
        docker login ghcr.io -u bognarpal -p ${{secrets.GHCR_TOKEN}}
        docker push ghcr.io/bognarpal/webtest4azure:$IMAGE_TAG
        docker push ghcr.io/bognarpal/webtest4azure:latest
        
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'Test-13A-B'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_30b7591f2e544ccdbb77948e6d5d825a }}
        images: 'ghcr.io/bognarpal/webtest4azure:${{ env.IMAGE_TAG }}'        
